# Generated by Django 3.1.2 on 2021-03-18 19:07

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('imagem', models.ImageField(blank=True, help_text='A image for your artigo', null=True, upload_to='')),
                ('texto', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
