# Generated by Django 3.1.2 on 2021-03-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210320_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='titulo',
            field=models.CharField(max_length=299),
        ),
    ]
