# Generated by Django 3.1.2 on 2021-03-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210322_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topico', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['topico'],
            },
        ),
        migrations.AddField(
            model_name='artigo',
            name='topicos',
            field=models.ManyToManyField(related_name='blog_artigotopico', to='blog.Topico'),
        ),
    ]
